### ISSUE TITLE
Any call to super.xzy() will satify the @CallSuper check

### ISSUE THREAD

**Issue by mstevens83** [kotcrab/callsuper-annotation#2]
Looking at your code I noticed the `@CallSuper` check is really easy to fool.
Consider this:

```
import com.kotcrab.annotation.CallSuper;

public class SuperClass {
    @CallSuper
    public void callMe () {
    }

    public void someOtherMethod () {}
}
```

And then this:

```
abstract class TestClass extends SuperClass {
    @Override //overriding method must be annotated with @Override
    public void callMe () {
        super.someOtherMethod(); // this is not the right super method but there is no compile error
    }
}
```

I agree this is scenario won't be common, but it's perfectly acceptable Java. So I'm afraid this check may be a bit too naive: https://github.com/kotcrab/callsuper-annotation/blob/master/src/com/kotcrab/annotation/callsuper/CallSuperProcessor.java#L74

It makes me wonder how Google implemented their version of the `@CallSuper` annotation. I haven't been able to find source code for their processor, have you?

**Comment by kotcrab** [comment]
Are you sure about it? It gives valid error for me. https://github.com/kotcrab/callsuper-annotation/blob/master/src/com/kotcrab/annotation/callsuper/CallSuperProcessor.java#L74 here it checks that is has `super.` and then if there is method name that is being checked.

I've no idea how Google made it, I don't even know if it's public already. From what they showed at Google IO I assume they made some plugin for Android Studio that checks it because their solution was showing errors in IDE with option to quick fix it.

**Comment by mstevens83** [comment]
Oops I must have done something wrong then. I'll double check.

**Comment by mstevens83** [comment]
You are right, it does work like it should. There must have been something wrong with my test case. Sorry.
